### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Autolinker' of undefined

### ISSUE THREAD

**Issue by bobiblazeski** [acdlite/react-remarkable#10]
I'm trying to use with React webpack project
(function (root, factory) {
        if (true) {
            // AMD. Register as an anonymous module unless amdModuleId is set
            !(**WEBPACK_AMD_DEFINE_ARRAY** = [], **WEBPACK_AMD_DEFINE_RESULT** = function () {
                return root['Autolinker'] = factory();
            }.apply(exports, **WEBPACK_AMD_DEFINE_ARRAY**), **WEBPACK_AMD_DEFINE_RESULT** !== undefined && (module.exports = **WEBPACK_AMD_DEFINE_RESULT**));
        } else if (typeof exports === 'object') {
            // Node. Does not work with strict CommonJS, but
            // only CommonJS-like environments that support module.exports,
            // like Node.
            module.exports = factory();
        } else {
            root['Autolinker'] = factory();
        }

**Comment by juanpaulo** [comment]
I'm having the same issue. Have you figured it out @bobiblazeski ?

**Comment by bobiblazeski** [comment]
@juanpaulo Sorry I don't work on that project anymore and don't remember did I solved it or used other library. :(

**Comment by kswgit** [comment]
@juanpaulo I fixed it but this is not ideal. Have you found another way?

edit 

node_modules/remarkable/node_modules/autolinker/dist/Autolinker.js

```
2 if (typeof define === 'function' && define.amd) {
```
to
```
2  if ( root && typeof define === 'function' && define.amd) {
```

https://github.com/gregjacobs/Autolinker.js/issues/86#issuecomment-107142262
https://github.com/LeZuse/Autolinker.js/commit/cb8fcc5d5c840f20c6cdd9532d1f77fcd0d6b5dc

**Comment by mxstbr** [comment]
Can't replicate this, hope y'all figured out the issue!
