### ISSUE TITLE
react-markdown-it does has error when compiled with webpack

### ISSUE THREAD

**Issue by geyang** [acdlite/react-remarkable#16]
@sunflowerdeath your fork does not have an issue tracker, so I am adding this issue here.

When react-markdown-it is compiled with webpack, we get the following message:

<img width="726" alt="screenshot 2016-06-24 11 43 43" src="https://cloud.githubusercontent.com/assets/630490/16347381/435b7424-3a01-11e6-98f0-a42c13d2a3ce.png">

It might make sense to open up the issues page on your repo.

@acdlite sorry to post this here! one of the forks that is published under the name `react-markdown-it` does not have a issues page because it is a fork.

**Comment by mxstbr** [comment]
This does not make any sense to be here, going to close it out.

**Comment by geyang** [comment]
@mxstbr Hey I think it might make sense for you to turn on the "Allow issues in forked projects" option in the settings. That way these issues could be reported on those forks instead.

Thanks for this library!
