### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by IcanDivideBy0** [acdlite/react-remarkable#19]
Hello,
Is this project still maintained ? Last commit is 2 years old and some PRs are marked LGTM since a while.
I'd be happy to help out if you are looking for co-maintainers ;)
Cheers!

**Comment by IcanDivideBy0** [comment]
ping @acdlite ?

**Comment by Venryx** [comment]
@There is this alternative, which seems to be a little better maintained: https://github.com/HHogg/remarkable-react (it's at least had a few commits in the last few months)

I also like how you can plug in your own react components for rendering the different elements returned by Remarkable.

However, you can't just use it as a react component. You have to use it in the render function of a "wrapper" component, like this:
```
class MarkdownWrapper extends BaseComponent<{source: string}, {}> {
	markdown: Remarkable;
	InitMarkdown() {
		this.markdown = new Remarkable();
		this.markdown.renderer = new RemarkableReactRenderer();
	}

	render() {
		let {source, ...rest} = this.props;

		if (this.markdown == null) {
			this.InitMarkdown();
		}

		let markdownResult = this.markdown.render(source);
		return (
			<div>
				{markdownResult}
			</div>
		);
	}
}
```

**Comment by Venryx** [comment]
There's also this, however it doesn't support tables, which is a big problem for me: https://github.com/rexxars/react-markdown

**Comment by svachalek** [comment]
I had this fall over when I tried upgrading to the 16 beta, so I replaced it with this snippet. It doesn't support any props but children but they're not that hard to add if you need 'em:

```
import Markdown from 'remarkable';

function ReactMarkdown({ children }) {
    const md = new Markdown();
    return React.Children.map(children, child => {
        if (typeof child === 'string') {
            return <span dangerouslySetInnerHTML={{ __html: md.render(child) }} />;
        } else {
            return child;
        }
    });
}
```

(note that this is taking advantage of the new ability to return an array from render, and would need to be wrapped on pre-16 builds)

**Comment by IcanDivideBy0** [comment]
Finally got an answer from @acdlite on twitter:

> get fucked

Not sure I want to help anymore on this project anymore

**Comment by Venryx** [comment]
That is an... odd response. Must be some context? Or maybe wrong person?

Software developers on Github tend to be pretty courteous in my experience, so it's odd that the creator would just instantly turn conversation off in two words like that. (though of course, there are sure to be exceptions) Why go through the trouble of putting it up online if you didn't care about others using it?
