### ISSUE TITLE
New lines aren't respected

### ISSUE THREAD

**Issue by matthewmueller** [acdlite/react-remarkable#4]
Doesn't seem like new lines for paragraphs are respected when you pass a string into <Markdown>.

Here's what I have:

``` js
<Markdown>
            ### 1.0 Got 15 minutes to learn how to value Facebook ###

            Come up with your own ‘fair value’ for stock, using the discounted cash flow (DCF)
            method in five easy steps. In this interactive walkthrough, we’ll show you how to
            calculate your own estimate for a ‘stock price’ by valuing the cash you think the
            company can generate.

            Pick one of these companies to start:
</Markdown>
```

Resulting in: 

![img](https://cldup.com/cwrlsZg0fl.png)

**Comment by matthewmueller** [comment]
^ Yah, the example on the readme actually doesn't work at all.

**Comment by mik01aj** [comment]
This is because Babel compiles this to a single line:

[![screenshot 2015-10-28 17 21 42](https://cloud.githubusercontent.com/assets/3027415/10795095/6447502a-7d98-11e5-8e0d-7eaf5b346103.png)](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%3CMarkdown%3E%0A%20%20%23%23%23%201.0%20Got%2015%20minutes%20to%20learn%20how%20to%20value%20Facebook%20%23%23%23%0A%0A%20%20Come%20up%20with%20your%20own%20%E2%80%98fair%20value%E2%80%99%20for%20stock%2C%20using%20the%20discounted%20cash%20flow%20%28DCF%29%0A%20%20method%20in%20five%20easy%20steps.%20In%20this%20interactive%20walkthrough%2C%20we%E2%80%99ll%20show%20you%20how%20to%0A%20%20calculate%20your%20own%20estimate%20for%20a%20%E2%80%98stock%20price%E2%80%99%20by%20valuing%20the%20cash%20you%20think%20the%0A%20%20company%20can%20generate.%0A%0A%20%20Pick%20one%20of%20these%20companies%20to%20start%3A%0A%3C%2FMarkdown%3E)

Sadly, this doesn't look like fixable...

**Comment by hamsterready** [comment]
``` js
var Cls = React.createClass({
  md: `
### hello

 1. list 1
 1. list 2

  `,

  render: function() {
    return (
        <Markdown>{this.md}</Markdown>
      );
  }
});
```

This one will work, check https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/template_strings#Multi-line_strings

**Comment by ChrisRus** [comment]
Previous example  from @hamsterready works for me in native JavaScript alright but fails to pass through babel's react preset unscathed when the same syntax is used in JSX as noted by @mik01aj.

In my project, I have a strong requirement to make it simple to drop <Markdown /> into the render functions of other React components that are defined by JSX and transpiled at build-time via webpack/babel/es2015/react presets.

My thought at this point is that the simplest pattern would be to rely on a webpack loader to pull the markdown source string from a plain text file into JSX module scope where it could be passed off via `<Markdown source={{webpackLoadedMarkdownSourceString}} />`.

If I have any success w/this approach I'll circle back here and leave some breadcrumbs.

**Comment by ChrisRus** [comment]
Check this:

``` JavaScipt
// This is JSX w/stuff you don't care about cut out.
const mds = require('./markdown.md');
module.exports = React.createClass({
    render: function() {
        return (<div>
                <Heading {...this.props} heading="Long content string 1" size="1" />
                <Markdown source={mds} />
                </div>
               );
    }
});
```

Works for me for both server & client-side renders produced by my webpack configuration.

If you simply add the import of the raw Markdown source string using `require` as shown above, your webpack will balk and tell you that a custom loader is required.

I just used the `raw-loader`:

```
npm install raw-loader --save
```

And then added a loader object to the relevant webpack configs to get this working:

``` JavaScript
const webpackConfig = {
   /// leaving some stuff out here obviously...
   loaders: {
                     {
                        test: /\.md$/,
                        loader: 'raw'
                    },
    }
};
```

This seems like a decent solution?

**Comment by abritinthebay** [comment]
Easiest solution is to use a template string.

```
<Markdown>
  {`### 1.0 Got 15 minutes to learn how to value Facebook ###

  Come up with your own ‘fair value’ for stock, using the discounted cash flow (DCF)
  method in five easy steps. In this interactive walkthrough, we’ll show you how to
  calculate your own estimate for a ‘stock price’ by valuing the cash you think the
  company can generate.

  Pick one of these companies to start:`}
</Markdown>
```

This will work as intended. As stated - this is an issue caused by parsing with Babel.

**Comment by jimthedev** [comment]
Additionally if you are using atom you can get markdown syntax highlighting in the blocks by going to Settings > Packages > language-babel Settings > Enter this for JavaScript Tagged Literal Grammar Extensions:

`"(?<=<Markdown>{)":source.gfm`

<img width="527" alt="screen shot 2017-05-28 at 9 04 27 am" src="https://cloud.githubusercontent.com/assets/108938/26529400/fe7ea216-4384-11e7-9eab-3259eb684648.png">
<img width="449" alt="screen shot 2017-05-28 at 9 06 31 am" src="https://cloud.githubusercontent.com/assets/108938/26529401/fe7faf4e-4384-11e7-8977-f1fe39537524.png">

 I'll put a PR in for the readme as well.
