### ISSUE TITLE
replace default components (i.e. <a> by <Link>)

### ISSUE THREAD

**Issue by luisrudge** [acdlite/react-remarkable#9]
I want to render relative links to my app (think a comments section), but I need to replace <a> by <Link> to make this work.

**Comment by babsonmatt** [comment]
Did you have any luck with this?

**Comment by luisrudge** [comment]
I'm using https://github.com/sunflowerdeath/react-markdown (which uses markdown-it) and passing this as props:

```
const handleIterate = (Tag, props, children) => {
  if (Tag === 'a' && props.href && props.href[0] === '/') {
    return <Link to={props.href}>{children}</Link>
  }
  return <Tag {...props}>{children}</Tag>;
}
```

**Comment by babsonmatt** [comment]
Thanks @luisrudge

**Comment by babsonmatt** [comment]
@luisrudge I just took a look at that lib, just had a quick question - what are you passing that function above to as props? Thanks

**Comment by luisrudge** [comment]
``` js
const handleIterate = (Tag, props, children) => {
  if (Tag === 'a' && props.href && props.href[0] === '/') {
    return <Link to={props.href}>{children}</Link>
  }
  return <Tag {...props}>{children}</Tag>;
}

<Markdown options={{handleIterate}}>
```

**Comment by babsonmatt** [comment]
Thanks @luisrudge, but what's actually running that handleIterate on the markdown-it side of things that's letting you iterate by tag? That doesn't appear to be an option out of the box unless I'm just not seeing it.. thanks again.

**Comment by luisrudge** [comment]
I'm soooooooooooooooooooo sorry! I gave you the wrong url :(
This is the actual component I'm using: https://github.com/alexkuz/markdown-react-js#using-custom-component-renderer

**Comment by babsonmatt** [comment]
Haha, don't worry about it!  Safe to say this makes much more sense now lol.  Out of curiosity, have you attempted to parse any markdown directly to a React component instead of going from html to React via the handleIterate approach?  Wondering if such a thing is possible and what the best approach might be there... thanks again for your help @luisrudge

**Comment by luisrudge** [comment]
Nope. I didn't try that. I just needed to replace `<a>` tags by `<Link>` components
